language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - sudo apt-get update
  - sudo apt-get -y --force-yes --reinstall install imagemagick
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-clover=coverage.xml

install:
  - pecl install imagick
  - composer require --dev
