language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install imagemagick
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - php -i

install:
  - composer require --dev
